- name: configure wordpress
  hosts: value_artem_wordpress_server
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-bucket-reflection21
    ansible_aws_ssm_region: eu-north-1
  roles:
    - wordpress
