---
- name: update
  apt:
    update_cache: true
  become: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags: docker

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  notify: update_cache_docker
  tags: install_docker

# install Docker и docker compose v2 plugin
- name: Install Docker and docker-compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  notify: restart_docker
  become: true
  tags: install_docker

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: true
  become: true
  tags: install_docker

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: "0644"
  become: true
  tags: install_wordpress

- name: Start docker-compose
  community.docker.docker_compose_v2:
    project_src: /home/ubuntu/
    state: present
  become: true
  tags: install_wordpress
## 2
# - name: /home/ubuntu/site_2
#   ansible.builtin.file:
#     path: /home/ubuntu/site_2  # путь к папке
#     state: directory               # обязательно указываем, что создаем директорию
#     owner: ubuntu                  # владелец (необязательно)
#     group: ubuntu                  # группа (необязательно)
#     mode: "0755"                   # права доступа (необязательно)
#   become: true
#   tags: install_wordpress

# - name: Copy docker-compose2.yml
#   copy:
#     src: docker-compose2.yml
#     dest: /home/ubuntu/site_2/docker-compose.yml
#     owner: ubuntu
#     group: ubuntu
#     mode: "0755"
#   become: true
#   tags: install_wordpress

# - name: Start docker-compose2
#   community.docker.docker_compose_v2:
#     project_src: /home/ubuntu/site_2/
#     state: present
#   become: true
#   tags: install_wordpress
